package view;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Locale;

import model.Nutzer;

/**
 * Die Klasse Credits_UI stellt die Benutzeroberfläche für das Credits-Fenster dar
 * Sie zeigt die Namen der Entwickler an und ermöglicht die Rückkehr zum Hauptmenü
 *
 * @author Bayezid, Farhan
 * @version 1.0
 */
public class Credits_UI {
    /**
     * Haupt-JPanel für das Credits-Fenster
     */
    private JPanel panel1;

    /**
     * Button zur Rückkehr zum Hauptmenü
     */
    private JButton zurückButton;

    /**
     * Label für das Quizzy-Logo Titteltext
     */
    private JLabel Quizzy;

    /**
     * Container-JPanel für das Credits-Fenster
     */
    private JPanel creditspanel;

    /**
     * Label zur Anzeige des angemeldeten Nutzers
     */
    private JLabel Spielername;

    /**
     * Referenz auf den aktuell angemeldeten Nutzer
     */
    private Nutzer currentUser;

    /**
     * Konstruktor für Credits_UI
     *
     * @param nutzer aktuell angemeldeter Nutzer
     */
    public Credits_UI(Nutzer nutzer) {
        this.currentUser = nutzer;
        Spielername.setText("Angemeldet als: " + currentUser.getName());
        zurückButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                MainFrame.switchToPanel(new MainFrame(currentUser).getMainPanel());
            }
        });
    }

    /**
     * Gibt das Haupt-JPanel für das Credits-Fenster zurück
     *
     * @return Haupt-JPanel
     */
    public JPanel getMainPanel() {
        return creditspanel;
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        creditspanel = new JPanel();
        creditspanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 3, new Insets(10, 10, 10, 10), -1, -1, true, false));
        creditspanel.setBackground(new Color(-1773569));
        creditspanel.setEnabled(false);
        creditspanel.setPreferredSize(new Dimension(700, 350));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(5, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel2.setAutoscrolls(false);
        panel2.setBackground(new Color(-1773569));
        creditspanel.add(panel2, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(300, 306), null, 0, false));
        zurückButton = new JButton();
        zurückButton.setBackground(new Color(-12580));
        zurückButton.setBorderPainted(true);
        zurückButton.setContentAreaFilled(false);
        zurückButton.setDefaultCapable(true);
        zurückButton.setDoubleBuffered(false);
        zurückButton.setEnabled(true);
        zurückButton.setFocusCycleRoot(true);
        zurückButton.setFocusPainted(true);
        zurückButton.setFocusable(true);
        Font zurückButtonFont = this.$$$getFont$$$("Arial Black", -1, -1, zurückButton.getFont());
        if (zurückButtonFont != null) zurückButton.setFont(zurückButtonFont);
        zurückButton.setForeground(new Color(-16579836));
        zurückButton.setHideActionText(false);
        zurückButton.setOpaque(true);
        zurückButton.setText("Zurück");
        zurückButton.putClientProperty("hideActionText", Boolean.FALSE);
        panel2.add(zurückButton, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(200, 40), null, 0, false));
        Quizzy = new JLabel();
        Quizzy.setEnabled(true);
        Font QuizzyFont = this.$$$getFont$$$("Arial Black", -1, 36, Quizzy.getFont());
        if (QuizzyFont != null) Quizzy.setFont(QuizzyFont);
        Quizzy.setForeground(new Color(-13887279));
        Quizzy.setHorizontalAlignment(0);
        Quizzy.setHorizontalTextPosition(0);
        Quizzy.setText("Quizzy!");
        panel2.add(Quizzy, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(126, 122), null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setBackground(new Color(-16579836));
        Font label1Font = this.$$$getFont$$$(null, Font.BOLD, 18, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setForeground(new Color(-16579836));
        label1.setText("Erstellt von:");
        label1.setVerticalAlignment(3);
        panel2.add(label1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setBackground(new Color(-16579836));
        Font label2Font = this.$$$getFont$$$(null, -1, 14, label2.getFont());
        if (label2Font != null) label2.setFont(label2Font);
        label2.setForeground(new Color(-16579836));
        label2.setText("Bayezid Yekda");
        label2.setVerticalAlignment(0);
        panel2.add(label2, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setBackground(new Color(-16579836));
        Font label3Font = this.$$$getFont$$$(null, -1, 14, label3.getFont());
        if (label3Font != null) label3.setFont(label3Font);
        label3.setForeground(new Color(-16579836));
        label3.setText("Farhan Seifaldeen");
        label3.setVerticalAlignment(1);
        label3.setVerticalTextPosition(0);
        panel2.add(label3, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setForeground(new Color(-9406850));
        label4.setText("Credits");
        creditspanel.add(label4, new com.intellij.uiDesigner.core.GridConstraints(1, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        Spielername = new JLabel();
        Spielername.setForeground(new Color(-9406850));
        Spielername.setText("Angemeldet als: shouldnotbeempty");
        creditspanel.add(Spielername, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return creditspanel;
    }


}
