package view;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Locale;
import java.util.List;

import model.Nutzer;
import controller.NutzerController;

/**
 * Die Klasse Highscore_UI stellt die  grafische Benutzeroberfläche für die Bestenliste bereit
 * Sie zeigt eine tabellarische Übersicht aller registrierten Nutzer,
 * sortiert nach deren erreichten Höchstpunktzahlen (Highscore) Zudem wird der persöhnliche Bestwert
 * des aktuell angemeldeten Nutzers angezeigt
 *
 * @author bayezid & Farhan
 * @version 1.0
 */
public class Highscore_UI {
    /** Hauptpanel, das alle Komponenten der Highscore-Ansicht enthält */
    private JPanel panel1;
    /** Button zur Rückkehr zum Hauptmenü*/
    private JButton zurückButton;
    /** Tabelle zur Anzeige der Rangliste (Platz, Name, Highscore)*/
    private JTable table1;
    /** Label zur Anzeige des Highscores des aktuellen Nutzers*/
    private JLabel numberlabel;
    /** Label zur Anzeige des aktuell angemeldeten Nutzers*/
    private JLabel spielernamebug;

    /** Referenz auf den aktuell angemeldeten Nutzer*/
    private Nutzer currentuser;

    /**
     * Konstruktor der Highscore_UI
     * Initialisiert die grafische Benutzeroberfläche, setzt die Texte fpr den aktuellen Nutzer,
     * lädt die Nutzerliste über den NutzerController und bereitet die Bestenliste durch Sortierung
     * (absteigend nach Punktzzahl) auf
     * @param nutzer der aktuell angemeldete Nutzer
     */
    public Highscore_UI(Nutzer nutzer) {
        this.currentuser = nutzer;

        spielernamebug.setText("Angemeldet als: " + currentuser.getName());
        numberlabel.setText(String.valueOf("Dein Highscore ist: " + currentuser.getHighscore()) + "!");

        zurückButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                MainFrame.switchToPanel(new MainFrame(currentuser).getMainPanel());
            }
        });

        NutzerController nutzerController = new NutzerController();
        List<Nutzer> nutzerList = nutzerController.getAllNutzer();

        // Sortieren nach Highscore (absteigend)
        nutzerList.sort((n1, n2) -> Integer.compare(n2.getHighscore(), n1.getHighscore()));

        String[] columnNames = {"Platz", "Name", "Highscore"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        int rank = 1;
        for (Nutzer n : nutzerList) {
            model.addRow(new Object[]{rank++, n.getName(), n.getHighscore()});
        }
        table1.setModel(model);

        // Spaltenbreiten anpassen
        TableColumnModel columnModel = table1.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(50);  // Platz
        columnModel.getColumn(1).setPreferredWidth(100); // Name
        columnModel.getColumn(2).setPreferredWidth(100); // Highscore
    }

    /**
     * Gibt das Haupt-Panel dieser Ansicht zurück
     * @return das JPanel der Highscore-UI
     */
    public JPanel getMainPanel() {
        return panel1;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 2, new Insets(10, 10, 10, 10), -1, -1, true, false));
        panel1.setBackground(new Color(-1773826));
        panel1.setForeground(new Color(-9406850));
        panel1.setPreferredSize(new Dimension(700, 350));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel2.setAutoscrolls(false);
        panel2.setBackground(new Color(-1773569));
        panel1.add(panel2, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(300, 306), null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setBackground(new Color(-1773826));
        scrollPane1.setFocusable(false);
        scrollPane1.setForeground(new Color(-1773826));
        scrollPane1.setRequestFocusEnabled(false);
        scrollPane1.setVerifyInputWhenFocusTarget(false);
        panel2.add(scrollPane1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(200, -1), null, 0, false));
        table1 = new JTable();
        table1.setAutoCreateColumnsFromModel(true);
        table1.setBackground(new Color(-1773826));
        table1.setEnabled(true);
        table1.setForeground(new Color(-16579836));
        table1.setOpaque(false);
        table1.setRequestFocusEnabled(false);
        table1.setRowSelectionAllowed(false);
        table1.setShowVerticalLines(true);
        scrollPane1.setViewportView(table1);
        zurückButton = new JButton();
        zurückButton.setBackground(new Color(-12580));
        zurückButton.setBorderPainted(true);
        zurückButton.setContentAreaFilled(false);
        zurückButton.setDefaultCapable(true);
        zurückButton.setDoubleBuffered(false);
        zurückButton.setEnabled(true);
        zurückButton.setFocusCycleRoot(true);
        zurückButton.setFocusPainted(true);
        zurückButton.setFocusable(true);
        Font zurückButtonFont = this.$$$getFont$$$("Arial Black", -1, -1, zurückButton.getFont());
        if (zurückButtonFont != null) zurückButton.setFont(zurückButtonFont);
        zurückButton.setForeground(new Color(-16579836));
        zurückButton.setHideActionText(false);
        zurückButton.setOpaque(true);
        zurückButton.setText("Zurück");
        zurückButton.putClientProperty("hideActionText", Boolean.FALSE);
        panel2.add(zurückButton, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(200, 40), null, 0, false));
        numberlabel = new JLabel();
        Font numberlabelFont = this.$$$getFont$$$("Arial Black", -1, 36, numberlabel.getFont());
        if (numberlabelFont != null) numberlabel.setFont(numberlabelFont);
        numberlabel.setForeground(new Color(-13887279));
        numberlabel.setText("200!");
        panel2.add(numberlabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        spielernamebug = new JLabel();
        spielernamebug.setForeground(new Color(-9406850));
        spielernamebug.setText("Angemeldet als: shouldnotbeempty");
        panel1.add(spielernamebug, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setForeground(new Color(-9406850));
        label1.setHorizontalAlignment(4);
        label1.setText("Highscore");
        panel1.add(label1, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}