package view;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.util.Locale;
import controller.NutzerController;
import model.Nutzer;

/**
 * Die Klasse Login_UI stellt die grafische Benutzeroberfläche für den Anmelde-Bildschirm bereit.
 * Sie ermöglicht dem Benutzer:
 *     Sich mit einem bestehenden Benutzernamen einzuloggen.</li>
 *     Einen neuen Benutzeraccount zu erstellen, falls der Name nicht gefunden wird.</li>
 *     Die Anwendung zu beenden.</li>
 *
 * Die Klasse nutzt den NutzerController für die Validierung und Erstellung von Nutzerdaten.
 *
 *
 * @author Farhan Bayezid
 * @version 1.0
 */
public class Login_UI {
    private JPanel panel1;
    private JLabel Quizzy;
    private JTextField benutzernameTextField;
    private JButton anmeldenButton;
    private JButton beendenButton;

    /**
     * Konstruktor der Klasse Login_UI.
     * Initialisiert die Benutzeroberfläche und registriert die ActionListener für die Buttons
     * sowie die Ereignisbehandlung für das Textfeld (Login per Enter-Taste und Placeholder-Logik).
     */
    public Login_UI() {

        $$$setupUI$$$();
        beendenButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.exit(0);
            }
        });

        anmeldenButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                performLogin();
            }
        });

        benutzernameTextField.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                performLogin();
            }
        });

        benutzernameTextField.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                super.focusGained(e);
                if (benutzernameTextField.getText().equals("Benutzername")) {
                    benutzernameTextField.setText("");
                    anmeldenButton.setEnabled(true);
                }
            }
        });
    }

    /**
     * Führt die Login-Logik aus.
     * Die Methode liest den Benutzernamen aus dem Textfeld aus und validiert diesen.
     * Existiert der Nutzer bereits, wird zum MainFrame gewechselt.
     * Existiert der Nutzer nicht, wird ein Dialog zur Erstellung eines neuen Profils angezeigt.
     */
    private void performLogin() {
        String benutzername = benutzernameTextField.getText();
        if (benutzername.equals("Benutzername") || benutzername.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Bitte geben Sie Ihren Benutzernamen ein!", "Fehler", JOptionPane.ERROR_MESSAGE);
            return;
        }

        NutzerController controller = new NutzerController();
        if (controller.checkNutzer(benutzername)) {
            Nutzer nutzer = controller.login(benutzername);

            MainFrame.switchToPanel(new MainFrame(nutzer).getMainPanel());
        } else {
            int input = JOptionPane.showConfirmDialog(null,
                    "Nutzer nicht gefunden! Möchten Sie einen neuen Nutzer erstellen?", "Nutzer nicht gefunden",
                    JOptionPane.YES_NO_OPTION);
            if (input == JOptionPane.YES_OPTION) {
                controller.createNutzer(benutzername, 0, false);
                JOptionPane.showMessageDialog(null, "Nutzer erfolgreich erstellt!");
            }
        }
    }

    /**
     * Liefert das Haupt-Panel der Login-Oberfläche zurück.
     * Dies wird benötigt, um den Inhalt im übergeordneten JFrame auszutauschen.
     *
     * @return Das JPanel, welches die Login-Komponenten enthält.
     */
    public JPanel getMainPanel() {
        return panel1;
    }


    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(10, 10, 10, 10), -1, -1));
        panel1.setBackground(new Color(-2036998));
        panel1.setPreferredSize(new Dimension(700, 350));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(5, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel2.setBackground(new Color(-2036998));
        panel1.add(panel2, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        panel2.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        benutzernameTextField = new JTextField();
        Font benutzernameTextFieldFont = this.$$$getFont$$$(null, Font.BOLD, 19, benutzernameTextField.getFont());
        if (benutzernameTextFieldFont != null) benutzernameTextField.setFont(benutzernameTextFieldFont);
        benutzernameTextField.setHorizontalAlignment(0);
        panel2.add(benutzernameTextField, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(410, 40), null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 2, new Insets(5, 0, 0, 0), -1, -1));
        panel3.setBackground(new Color(-2036998));
        panel2.add(panel3, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        beendenButton = new JButton();
        beendenButton.setBackground(new Color(-12580));
        beendenButton.setBorderPainted(true);
        beendenButton.setContentAreaFilled(false);
        beendenButton.setDefaultCapable(true);
        beendenButton.setDoubleBuffered(false);
        beendenButton.setEnabled(true);
        beendenButton.setFocusCycleRoot(true);
        beendenButton.setFocusPainted(true);
        beendenButton.setFocusable(true);
        Font beendenButtonFont = this.$$$getFont$$$("Arial Black", -1, -1, beendenButton.getFont());
        if (beendenButtonFont != null) beendenButton.setFont(beendenButtonFont);
        beendenButton.setForeground(new Color(-16579836));
        beendenButton.setHideActionText(false);
        beendenButton.setOpaque(true);
        beendenButton.setText("Beenden");
        beendenButton.putClientProperty("hideActionText", Boolean.FALSE);
        panel3.add(beendenButton, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(200, 40), null, 0, false));
        anmeldenButton = new JButton();
        anmeldenButton.setBackground(new Color(-3944740));
        anmeldenButton.setBorderPainted(true);
        anmeldenButton.setContentAreaFilled(false);
        anmeldenButton.setDefaultCapable(true);
        anmeldenButton.setDoubleBuffered(false);
        anmeldenButton.setEnabled(true);
        anmeldenButton.setFocusCycleRoot(true);
        anmeldenButton.setFocusPainted(true);
        anmeldenButton.setFocusable(true);
        Font anmeldenButtonFont = this.$$$getFont$$$("Arial Black", -1, -1, anmeldenButton.getFont());
        if (anmeldenButtonFont != null) anmeldenButton.setFont(anmeldenButtonFont);
        anmeldenButton.setForeground(new Color(-16579836));
        anmeldenButton.setHideActionText(false);
        anmeldenButton.setOpaque(true);
        anmeldenButton.setText("Anmelden");
        anmeldenButton.putClientProperty("hideActionText", Boolean.FALSE);
        panel3.add(anmeldenButton, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(200, 40), null, 0, false));
        Quizzy = new JLabel();
        Quizzy.setEnabled(true);
        Font QuizzyFont = this.$$$getFont$$$("Arial Black", -1, 36, Quizzy.getFont());
        if (QuizzyFont != null) Quizzy.setFont(QuizzyFont);
        Quizzy.setForeground(new Color(-13887279));
        Quizzy.setHorizontalAlignment(0);
        Quizzy.setHorizontalTextPosition(0);
        Quizzy.setText("Quizzy!");
        panel2.add(Quizzy, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(126, 122), null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer2 = new com.intellij.uiDesigner.core.Spacer();
        panel2.add(spacer2, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setForeground(new Color(-9406850));
        label1.setText("Login");
        panel1.add(label1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
