package view;

import model.Nutzer;

import controller.FragenController;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Locale;
/**
 * Die Klasse Spiele_UI stellt das Auswahlmenü für die verschiedenen Spielmodi bereit.
 *
 * In dieser Ansicht kann der Benutzer zwischen dem klassischen Quiz, dem
 * Herausforderungsmodus und dem Übungsmodus wählen. Die Klasse fungiert als
 * Zwischenschicht zwischen dem Hauptmenü und den eigentlichen Spiel-Oberflächen.
 *
 * Besonderheiten:
 * - Überprüfung der Datenquelle: Beim Initialisieren wird über den FragenController
 *   geprüft, ob Fragen in der CSV-Datei vorhanden sind.
 * - Fehlertoleranz: Falls keine Fragen gefunden werden, werden die Start-Buttons
 *   deaktiviert, um Laufzeitfehler zu verhindern.
 * - Navigationssteuerung: Verwaltet die Übergänge zu den spezifischen Spiel-UIs
 *   über das MainFrame.
 *
 * @author Farhan Bayezid
 * @version 1.0
 */
public class Spiele_UI {
    private JPanel panel1;
    private JLabel Spielername;
    private JButton quizButton;
    private JButton herausforderungButton;
    private JButton ubungsmodusButton;
    private JButton zurückButton;
    private JLabel Quizzy;
    /** Controller zur Überprüfung der geladenen Fragen aus der CSV-Datei. */
    private FragenController fragenController;

    /** Der aktuell angemeldete Benutzer. */
    private Nutzer currentUser;

    /**
     * Konstruktor der Spiele_UI.
     *
     * Erstellt die Benutzeroberfläche für die Modus-Auswahl. Dabei wird der
     * aktuelle Benutzername angezeigt und eine Validierung der Fragen-Datenbank
     * durchgeführt. Sind keine Fragen vorhanden, wird der Nutzer per Dialog
     * informiert und die Spielmodi gesperrt.
     *
     * Zudem werden die ActionListener für alle Buttons initialisiert, um die
     * entsprechende Navigation im MainFrame auszulösen.
     *
     * @param nutzer Der aktuell angemeldete Nutzer für die Session.
     */
    public Spiele_UI(Nutzer nutzer) {
        this.currentUser = nutzer;
        this.fragenController = new FragenController();
        Spielername.setText("Angemeldet als: " + currentUser.getName());

        if (this.fragenController.getLoadedQuestions().isEmpty()) {

            JOptionPane.showMessageDialog(panel1, "Es gibt keine Fragen in der CSV-Datei!", "Fehler", JOptionPane.ERROR_MESSAGE);
            quizButton.setEnabled(false);
            herausforderungButton.setEnabled(false);
            ubungsmodusButton.setEnabled(false);
        } else {
            quizButton.setEnabled(true);
            herausforderungButton.setEnabled(true);
            ubungsmodusButton.setEnabled(true);
        }

        zurückButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                MainFrame mainFrame = new MainFrame(currentUser);
                MainFrame.switchToPanel(mainFrame.getMainPanel());
            }
        });

        quizButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Quiz_UI quizUI = new Quiz_UI(currentUser);
                MainFrame.switchToPanel(quizUI.getMainPanel());
            }
        });
        herausforderungButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Herausforderung_UI herausforderungUI = new Herausforderung_UI(currentUser);
                MainFrame.switchToPanel(herausforderungUI.getMainPanel());
            }
        });
        ubungsmodusButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Ubungsmodus_UI ubungsmodusUI = new Ubungsmodus_UI(currentUser);
                MainFrame.switchToPanel(ubungsmodusUI.getMainPanel());
            }
        });
    }

    /**
     * Liefert das Haupt-Panel der Spielmodus-Auswahl zurück.
     *
     * @return Das JPanel, welches die Auswahl-Buttons und Labels enthält.
     */
    public JPanel getMainPanel() {
        return panel1;
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 2, new Insets(10, 10, 10, 10), -1, -1, true, false));
        panel1.setBackground(new Color(-1773569));
        panel1.setEnabled(true);
        panel1.setPreferredSize(new Dimension(700, 350));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(5, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel2.setAutoscrolls(false);
        panel2.setBackground(new Color(-1773569));
        panel1.add(panel2, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(300, 306), null, 0, false));
        quizButton = new JButton();
        quizButton.setAlignmentY(0.5f);
        quizButton.setBackground(new Color(-3944740));
        quizButton.setBorderPainted(true);
        quizButton.setEnabled(true);
        Font quizButtonFont = this.$$$getFont$$$("Arial Black", -1, -1, quizButton.getFont());
        if (quizButtonFont != null) quizButton.setFont(quizButtonFont);
        quizButton.setForeground(new Color(-16579836));
        quizButton.setHideActionText(false);
        quizButton.setText("Quiz");
        panel2.add(quizButton, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(200, 40), null, 0, false));
        herausforderungButton = new JButton();
        herausforderungButton.setBackground(new Color(-3944740));
        herausforderungButton.setBorderPainted(true);
        herausforderungButton.setEnabled(true);
        Font herausforderungButtonFont = this.$$$getFont$$$("Arial Black", -1, -1, herausforderungButton.getFont());
        if (herausforderungButtonFont != null) herausforderungButton.setFont(herausforderungButtonFont);
        herausforderungButton.setForeground(new Color(-16579836));
        herausforderungButton.setText("Herausforderung");
        panel2.add(herausforderungButton, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(200, 40), null, 0, false));
        ubungsmodusButton = new JButton();
        ubungsmodusButton.setBackground(new Color(-3944740));
        ubungsmodusButton.setBorderPainted(true);
        ubungsmodusButton.setContentAreaFilled(true);
        ubungsmodusButton.setDefaultCapable(true);
        ubungsmodusButton.setEnabled(true);
        ubungsmodusButton.setFocusPainted(true);
        ubungsmodusButton.setFocusable(true);
        Font ubungsmodusButtonFont = this.$$$getFont$$$("Arial Black", -1, -1, ubungsmodusButton.getFont());
        if (ubungsmodusButtonFont != null) ubungsmodusButton.setFont(ubungsmodusButtonFont);
        ubungsmodusButton.setForeground(new Color(-16579836));
        ubungsmodusButton.setHideActionText(false);
        ubungsmodusButton.setText("Übungsmodus");
        ubungsmodusButton.putClientProperty("hideActionText", Boolean.FALSE);
        panel2.add(ubungsmodusButton, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(200, 40), null, 0, false));
        zurückButton = new JButton();
        zurückButton.setBackground(new Color(-12580));
        zurückButton.setBorderPainted(true);
        zurückButton.setContentAreaFilled(false);
        zurückButton.setDefaultCapable(true);
        zurückButton.setDoubleBuffered(false);
        zurückButton.setEnabled(true);
        zurückButton.setFocusCycleRoot(true);
        zurückButton.setFocusPainted(true);
        zurückButton.setFocusable(true);
        Font zurückButtonFont = this.$$$getFont$$$("Arial Black", -1, -1, zurückButton.getFont());
        if (zurückButtonFont != null) zurückButton.setFont(zurückButtonFont);
        zurückButton.setForeground(new Color(-16579836));
        zurückButton.setHideActionText(false);
        zurückButton.setOpaque(true);
        zurückButton.setText("Zurück");
        zurückButton.putClientProperty("hideActionText", Boolean.FALSE);
        panel2.add(zurückButton, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(200, 40), null, 0, false));
        Quizzy = new JLabel();
        Quizzy.setEnabled(true);
        Font QuizzyFont = this.$$$getFont$$$("Arial Black", -1, 36, Quizzy.getFont());
        if (QuizzyFont != null) Quizzy.setFont(QuizzyFont);
        Quizzy.setForeground(new Color(-13887279));
        Quizzy.setHorizontalAlignment(0);
        Quizzy.setHorizontalTextPosition(0);
        Quizzy.setText("Spielen");
        panel2.add(Quizzy, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(126, 122), null, 0, false));
        Spielername = new JLabel();
        Spielername.setForeground(new Color(-9406850));
        Spielername.setText("Angemeldet als: shouldnotbeempty");
        panel1.add(Spielername, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setForeground(new Color(-9406850));
        label1.setText("Spielen");
        panel1.add(label1, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}